In [1]:
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import nltk
from pathlib import Path
from utils import dataset_path

In [2]:
data_path = Path("data")
count = 0
for mail_path in os.listdir(dataset_path):
    for path in os.listdir(dataset_path/ Path(mail_path) / data_path):
        if path.endswith('.csv'):
            if count == 0:
                df = pd.read_csv(dataset_path/ Path(mail_path) / data_path / Path(path))
                count += 1
            else:
                df = pd.concat([df, pd.read_csv(dataset_path/ Path(mail_path) / data_path / Path(path))], ignore_index=True)
print(df.value_counts('Reachable'))
print("Text is None: ",len(df[df['Text'].isna()]))
df = df.dropna(subset=['Text'])
df = df[df['Reachable']]
df = df.reset_index(drop=True)
print("Total number of texts to process: ",len(df))

Reachable
True     2039
False     647
Name: count, dtype: int64
Text is None:  748
Total number of texts to process:  1938

In [3]:
df.drop(['Links', 'Reachable','Code'], axis=1, inplace=True)

from transformers import BertTokenizer

# Load the BERT tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Text to tokenize
text = "Sample text to tokenize."

# Tokenize the text
tokens = tokenizer.tokenize(text)
print("Tokens:", tokens)

# Count the number of tokens
num_tokens = len(tokens)

print("Number of tokens:", num_tokens)

In [4]:
df = df.iloc[:200]

In [3]:
df

,Links,Reachable,Code,Text,Date
0,https://www.routledge.com/Routledge-Internatio...,True,200,1st Edition\nRoutledge International Handbook ...,"Wed, 18 May 2016 09:44:26 -0000"
1,http://www.gala.fr/l_actu/culture/la_fille_inc...,True,200,"Pour la septième fois, Luc et Jean-Pierre Dard...","Fri, 20 May 2016 00:13:52 -0000"
2,http://ifp.nyu.edu/2016/journal-article-abstra...,True,200,Unraveling the Slut Narrative: Gender Constrai...,"Thu, 26 May 2016 09:44:26 -0000"
3,http://www.actuabd.com/Platinum-End-T1-Par-Tsu...,True,200,C’est le troisième gros lancement manga de l’a...,"Sat, 28 May 2016 08:14:14 -0000"
4,http://next.liberation.fr/cinema/2016/05/31/a-...,True,200,A War explore en deux temps les opérations mil...,"Wed, 01 Jun 2016 00:14:17 -0000"
...,...,...,...,...,...
1933,https://voi.id/en/news/377517,True,200,JAKARTA - The Corruption Eradication Commissio...,"Wed, 01 May 2024 12:40:50 -0000"
1934,https://dailyguardian.com.ph/first-light-a-shi...,True,200,"By Christine Marie Lim Magpile, LPT\nEast Meet...","Wed, 01 May 2024 12:40:50 -0000"
1935,https://www.thisislocallondon.co.uk/news/24290...,True,200,‘The Hunger Games’ book review\nSuzanne Collin...,"Wed, 01 May 2024 12:40:50 -0000"
1936,https://www.celluloidz.com/psycho/decouverte-s...,True,200,Au gré des swipes sur votre application de ren...,"Wed, 01 May 2024 15:13:52 -0000"
1937,https://news.dayfr.com/people/3753602.html,True,200,"Cette immense star hollywoodienne, auréolée de...","Thu, 02 May 2024 15:15:10 -0000"

In [4]:
df.to_csv('google_alerts/processed_data.csv', index=False)

In [6]:
stop_words = nltk.corpus.stopwords.words('french') + nltk.corpus.stopwords.words('english')
count_vect = CountVectorizer(max_df=0.5, min_df=0.1, stop_words=stop_words)
doc_term_matrix = count_vect.fit_transform(df['Text'].values)

In [7]:
nb_topics = 22

In [8]:
LDA = LatentDirichletAllocation(n_components=nb_topics, random_state=42)
LDA.fit(doc_term_matrix)

LatentDirichletAllocation(n_components=22, random_state=42)

In [9]:
first_topic = LDA.components_[0]
top_topic_words = first_topic.argsort()[-10:]
for i in top_topic_words:
    print(count_vect.get_feature_names_out()[i])

fin
militaire
depuis
très
pays
peut
ans
sans
contre
guerre

In [10]:
for i,topic in enumerate(LDA.components_):
    print(f'Top 10 words for topic #{i}:')
    print([count_vect.get_feature_names_out()[i] for i in topic.argsort()[-15:]])
    print('\n')

Top 10 words for topic #0:
['jour', 'jusqu', 'vie', 'attaque', 'avoir', 'fin', 'militaire', 'depuis', 'très', 'pays', 'peut', 'ans', 'sans', 'contre', 'guerre']


Top 10 words for topic #1:
['cela', 'choix', 'loi', 'selon', 'exemple', 'manière', 'peut', 'non', 'où', 'enfant', 'personnes', 'sans', 'décision', 'enfants', 'vie']


Top 10 words for topic #2:
['forme', 'nouvelle', 'décisions', 'sortie', 'personnages', 'septembre', 'histoire', 'monde', 'réalisé', 'états', 'écrit', 'unis', 'jeu', '2023', 'vidéo']


Top 10 words for topic #3:
['nouvelle', 'autres', 'faut', 'mis', 'premier', 'encore', 'effet', 'puis', 'rien', 'information', 'maintenant', 'jour', 'dit', '2023', 'vie']


Top 10 words for topic #4:
['selon', 'personnes', 'trouver', 'cela', 'groupe', 'peut', 'vie', 'sauver', 'nouvelle', 'pouvez', 'jeu', 'leurs', 'deux', 'également', 'choix']


Top 10 words for topic #5:
['celle', 'avoir', 'jusqu', 'pendant', 'millions', 'ans', 'prendre', 'fils', 'personne', 'ville', 'vie', 'mère', 'famille', 'meilleur', 'homme']


Top 10 words for topic #6:
['vivre', 'petite', 'conséquences', 'avoir', 'deux', 'ci', 'mis', 'homme', 'film', 'tuer', 'histoire', 'fils', '2023', 'celle', 'principal']


Top 10 words for topic #7:
['ad_2', 'ad_1', 'avant', 'utiliser', 'depuis', 'début', 'femme', 'homme', 'projet', 'pourrait', 'retrouve', 'ans', 'dernière', 'également', 'dernier']


Top 10 words for topic #8:
['font', 'père', 'femme', 'malgré', 'reste', 'temps', 'cinéma', 'sous', 'ans', 'nature', 'amour', 'films', 'vie', 'histoire', 'film']


Top 10 words for topic #9:
['beaucoup', 'où', 'ici', 'ça', 'cela', 'jamais', 'assez', 'octobre', 'trop', 'heure', 'va', 'histoire', 'peu', '2023', 'film']


Top 10 words for topic #10:
['ans', 'depuis', 'quand', 'va', 'autres', 'sous', 'pays', 'sans', 'petit', 'meilleur', '10', 'films', 'jeune', 'cinéma', 'comment']


Top 10 words for topic #11:
['éthique', 'met', 'action', 'également', 'rôle', 'nature', 'personnages', 'fiction', 'mal', 'temps', 'science', 'histoire', 'série', 'monde', 'film']


Top 10 words for topic #12:
['dire', 'beaucoup', 'cela', 'rien', 'avoir', 'deux', 'sans', 'leurs', 'autre', 'morale', 'dit', 'temps', 'très', 'autres', 'peut']


Top 10 words for topic #13:
['beaucoup', 'genre', 'petit', 'simple', 'trop', 'prix', 'enfant', 'femme', 'scène', 'question', 'travail', 'homme', 'dit', 'porte', 'cela']


Top 10 words for topic #14:
['dit', 'là', 'personnages', 'quelque', 'vraiment', 'chose', 'personnage', 'où', 'parce', 'cela', 'histoire', 'ça', 'série', 'épisode', 'saison']


Top 10 words for topic #15:
['dire', 'deux', 'nouveau', 'grand', 'autre', 'dont', 'films', 'quand', 'sortie', 'lors', 'film', 'vérité', 'morale', 'justice', 'éthique']


Top 10 words for topic #16:
['celle', 'moins', 'état', 'justice', 'public', 'très', 'politique', 'ailleurs', 'question', 'elles', 'femmes', 'france', 'droit', 'leurs', 'enfants']


Top 10 words for topic #17:
['prix', 'dont', 'première', 'homme', 'face', 'films', '2023', 'recherche', 'rôle', 'très', 'famille', 'père', 'réalisateur', 'projet', 'film']


Top 10 words for topic #18:
['histoire', 'famille', 'où', 'autres', 'avoir', 'ville', 'également', 'deux', 'quelques', 'cet', 'années', 'personnage', 'sous', 'livre', 'grand']


Top 10 words for topic #19:
['combat', 'sans', 'image', 'deux', 'leurs', 'tous', 'sous', 'doit', 'état', 'depuis', 'monde', 'contre', 'pays', 'conflit', 'guerre']


Top 10 words for topic #20:
['dont', 'donner', 'première', 'déjà', 'pouvoir', 'équipe', 'jeu', 'autre', 'quelques', 'peut', 'où', 'trois', 'mois', 'va', 'ligne']


Top 10 words for topic #21:
['côté', 'sauver', 'genre', 'fille', 'choix', 'ensuite', 'avoir', 'savoir', 'scènes', 'peut', 'cependant', 'afin', 'tuer', 'cela', 'fin']

# OTHER METHOD

In [11]:
nb_topics = 25

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vect = TfidfVectorizer(max_df=0.8, min_df=2, stop_words=stop_words)
doc_term_matrix = tfidf_vect.fit_transform(df['Text'].values.astype('U'))

In [13]:
from sklearn.decomposition import NMF

nmf = NMF(n_components=nb_topics, random_state=42)
nmf.fit(doc_term_matrix )

C:\Users\Emile\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\decomposition\_nmf.py:1770: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(

NMF(n_components=25, random_state=42)

In [14]:
components_df = pd.DataFrame(nmf.components_, columns=tfidf_vect.get_feature_names_out())
components_df

,00,000,01,02,03,04,05,06,07,08,...,événements,être,êtres,île,îles,œil,œuf,œufs,œuvre,œuvres
0,0.005385,0.170873,0.000000,0.000000,0.002367,0.000000,0.000000,0.000000,0.009052,0.030945,...,0.000000,0.343425,0.026917,0.019762,0.000564,0.002094,0.019215,0.001442,0.000000,0.010220
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000045,0.000035,...,0.000007,0.000031,0.000021,0.000000,0.000000,0.000000,0.000031,0.000078,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.002402,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.113389,0.000000,0.000000,0.003702,0.000000,0.000000,0.000000,0.010781,0.000000,...,0.000000,0.057061,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.016293,0.067119,0.000000,0.004248,0.000000,0.008282,0.000000,0.000000,0.001193,0.000000
5,0.012430,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.060986,0.025861,0.014757,0.000000,0.034287,0.000000,0.000000,0.000000,0.008632,0.000000
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000847,0.000000,0.000000,0.018103,0.000000,0.000000,0.000000,0.000000,0.000000
7,0.000304,0.000000,0.000000,0.000000,0.000000,0.000000,0.000402,0.000941,0.000000,0.000000,...,0.000000,0.000667,0.000121,0.000000,0.000088,0.000000,0.000000,0.000269,0.000000,0.000000
8,0.032368,0.000000,0.070916,0.018125,0.404410,1.088310,0.174061,0.085087,0.085993,0.081749,...,0.000000,0.005413,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.004016,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.020797,0.000000,0.000000,0.000000,...,0.084771,0.052788,0.001770,0.000000,0.000000,0.027914,0.043985,0.000000,0.042358,0.019588
10,0.000000,0.025627,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.008259,0.140370,0.000000,0.000000,0.000000,0.001307,0.000000,0.000000,0.000000,0.000000
11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000691,0.000000,0.000000,...,0.047774,0.077972,0.015822,0.000000,0.000000,0.000000,0.015245,0.031178,0.000000,0.000000
12,0.007416,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.007177,0.000000,0.000000,...,0.000000,0.085779,0.000000,0.000000,0.000000,0.000000,0.000000,0.000769,0.055336,0.000000
13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000093,...,0.018876,0.044875,0.000000,0.000000,0.000000,0.006826,0.000000,0.027997,0.000924,0.000000
14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.001939,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000053,0.000000,0.000000,0.000000,0.000000,0.001627
15,0.025180,0.000000,0.018293,0.000000,0.000000,0.018702,0.000000,0.000000,0.000000,0.000000,...,0.001464,0.009874,0.000000,0.000236,0.000000,0.001146,0.000000,0.000000,0.000909,0.000000
16,0.022826,0.000000,0.207592,0.335766,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.004255,0.091241,0.000522,0.000000,0.001119,0.000988,0.003580,0.000000
17,0.000000,0.000000,0.000000,0.000000,0.009038,0.000000,0.001629,0.001191,0.000000,0.000000,...,0.019966,0.140694,0.025754,0.000000,0.000000,0.008329,0.000000,0.000000,0.017315,0.000000
18,0.000000,0.159877,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.110447,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.002537,0.033516
19,0.000000,0.000000,0.000000,0.000364,0.000000,0.000000,0.001385,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.003973,0.003783
20,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.008129,0.001375,0.000000,0.000000,...,0.027022,0.052742,0.011606,0.003856,0.002320,0.000000,0.000000,0.000000,0.008336,0.000000
21,0.000000,0.002301,0.000000,0.000000,0.000000,0.000000,0.000113,0.000000,0.000000,0.000000,...,0.000000,0.002493,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.050381,0.000000
22,0.000000,0.004185,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.007723,0.000000,0.000000,0.001378,0.000000,0.000000,0.000000,0.003496,0.000000
23,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.034430,0.000000,0.000372,0.000000,0.000000,0.002516,0.000000,0.000000,0.000000
24,0.010191,0.000000,0.000000,0.000000,0.061078,0.000000,0.000000,0.011708,0.000000,0.000000,...,0.006154,0.071636,0.000000,0.000491,0.000362,0.000000,0.000000,0.000000,0.000000,0.000006

In [15]:
for topic in range(components_df.shape[0]):
    tmp = components_df.iloc[topic]
    print(f'For topic {topic+1} the words with the highest value are:')
    print(tmp.nlargest(10))
    print('\n')

For topic 1 the words with the highest value are:
plus     0.572026
si       0.520067
faire    0.422179
tout     0.400702
ça       0.376310
être     0.343425
cela     0.334194
comme    0.324634
fait     0.297794
dit      0.295537
Name: 0, dtype: float64


For topic 2 the words with the highest value are:
access           0.560786
apologize        0.560786
available        0.560786
inconvenience    0.560786
longer           0.560786
removed          0.560786
trying           0.560786
content          0.528514
ellie            0.000493
floride          0.000477
Name: 1, dtype: float64


For topic 3 the words with the highest value are:
hoult         0.650839
jouera        0.637429
juré          0.588060
eastwood      0.456718
collette      0.348354
sutherland    0.342023
procès        0.339205
deutch        0.305158
jury          0.278686
clint         0.246055
Name: 2, dtype: float64


For topic 4 the words with the highest value are:
hamas          0.827706
israël         0.627708
gaza           0.577712
otages         0.297221
israélienne    0.267966
hôpital        0.251195
tsahal         0.226564
israéliens     0.212391
guerre         0.201174
terroristes    0.185579
Name: 3, dtype: float64


For topic 5 the words with the highest value are:
russie       0.719862
guerre       0.703927
ukraine      0.701655
poutine      0.278420
russe        0.211110
sanctions    0.192726
contre       0.183657
russes       0.170119
pays         0.146736
moscou       0.122140
Name: 4, dtype: float64


For topic 6 the words with the highest value are:
oppenheimer    1.001717
bombe          0.415149
atomique       0.276151
manhattan      0.250550
nolan          0.239285
physicien      0.233782
robert         0.226967
murphy         0.211715
projet         0.183623
cillian        0.171308
Name: 5, dtype: float64


For topic 7 the words with the highest value are:
diaz            0.583546
lav             0.583546
hermes          0.479641
vagues          0.359751
philippines     0.346710
retirent        0.324512
hermès          0.252503
papauran        0.231085
lieutenant      0.227602
physiquement    0.215229
Name: 6, dtype: float64


For topic 8 the words with the highest value are:
sixième      0.411842
bonnard      0.383400
chemla       0.383400
giraudeau    0.383400
lavernhe     0.383400
damien       0.366475
sara         0.366095
enfant       0.348517
judith       0.340610
benjamin     0.329123
Name: 7, dtype: float64


For topic 9 the words with the highest value are:
04            1.088310
2024          0.755963
management    0.600545
a544a3        0.422948
03            0.404410
stratégie     0.382139
ffb742        0.331238
iqsog         0.331238
gestion       0.277389
25            0.259499
Name: 8, dtype: float64


For topic 10 the words with the highest value are:
film        1.063986
ford        0.300324
plus        0.202443
films       0.199294
histoire    0.195011
hard        0.187007
man         0.151627
réalisé     0.141216
suit        0.137453
monde       0.133608
Name: 9, dtype: float64


For topic 11 the words with the highest value are:
starfield    1.459205
vaisseau     0.546500
juno         0.506214
porrima      0.369520
ryujin       0.330343
crédits      0.315871
pouvez       0.306761
bethesda     0.301143
quête        0.285684
mme          0.278204
Name: 10, dtype: float64


For topic 12 the words with the highest value are:
joel      0.974925
ellie     0.868292
last      0.659547
us        0.635518
jeux      0.437832
jeu       0.409471
remède    0.315147
vidéo     0.309389
hbo       0.301102
mazin     0.278717
Name: 11, dtype: float64


For topic 13 the words with the highest value are:
enfants        0.771269
djihadistes    0.708531
france         0.396576
droit          0.378624
femmes         0.369818
syrie          0.341546
rapatrier      0.291003
leurs          0.244527
elles          0.222598
crimes         0.213518
Name: 12, dtype: float64


For topic 14 the words with the highest value are:
saison      0.729937
épisode     0.688773
série       0.345572
épisodes    0.268443
star        0.238447
trek        0.236280
netflix     0.229087
mirror      0.199224
black       0.176630
histoire    0.148452
Name: 13, dtype: float64


For topic 15 the words with the highest value are:
portman     0.323687
natalie     0.321693
haynes      0.287692
todd        0.287692
julianne    0.251698
cannes      0.244112
moore       0.219054
december    0.215769
robe        0.207912
may         0.198105
Name: 14, dtype: float64


For topic 16 the words with the highest value are:
antea          0.383837
eden           0.363216
banishers      0.354583
new            0.269323
xbox           0.237351
series         0.215036
vivants        0.212193
red            0.206742
playstation    0.197258
fantômes       0.183243
Name: 15, dtype: float64


For topic 17 the words with the highest value are:
2023         0.500360
02           0.335766
vegapunk     0.259139
fille        0.220203
petite       0.212099
cabin        0.210284
knock        0.210284
01           0.207592
shyamalan    0.198458
1er          0.197603
Name: 16, dtype: float64


For topic 18 the words with the highest value are:
valeurs         0.413180
éthique         0.411102
morale          0.331121
morales         0.261563
spinoza         0.202497
bien            0.175439
règles          0.169151
exemple         0.166327
enseignement    0.158870
entre           0.158761
Name: 17, dtype: float64


For topic 19 the words with the highest value are:
euros          0.359984
métier         0.165441
salaire        0.161320
entreprises    0.160741
000            0.159877
plus           0.153961
réseau         0.152959
animaux        0.141601
ceux           0.139402
twitter        0.129907
Name: 18, dtype: float64


For topic 20 the words with the highest value are:
principal    0.461585
roschdy      0.362244
zem          0.362244
collège      0.264151
chad         0.256875
chenouga     0.256875
sabri        0.197643
fils         0.174395
marina       0.164601
moreau       0.164601
Name: 19, dtype: float64


For topic 21 the words with the highest value are:
frank       0.246815
frère       0.218333
homme       0.202637
justice     0.181843
famille     0.150913
cette       0.142671
clan        0.131079
ans         0.124890
relation    0.124610
entre       0.123468
Name: 20, dtype: float64


For topic 22 the words with the highest value are:
jean             0.352081
homosexualité    0.326005
georgia          0.240763
oakley           0.240763
section          0.220554
film             0.216653
blue             0.193323
venise           0.181283
angleterre       0.158402
confronte        0.139863
Name: 21, dtype: float64


For topic 23 the words with the highest value are:
iran          0.410058
omid          0.378175
téhéran       0.336552
amini         0.277083
mahsa         0.277083
violations    0.266883
droits        0.261025
femme         0.245080
liberté       0.234481
iranien       0.207221
Name: 22, dtype: float64


For topic 24 the words with the highest value are:
ia              0.509959
edwards         0.303681
joshua          0.222090
alfie           0.212615
créateur        0.212156
artificielle    0.147971
science         0.143438
technologie     0.139935
fiction         0.139541
intelligence    0.136608
Name: 23, dtype: float64


For topic 25 the words with the highest value are:
chanteur        0.453481
déclaré         0.272551
artiste         0.210281
femmes          0.173502
chris           0.153815
pornographie    0.144411
bois            0.132948
révélé          0.129361
global          0.127745
tv              0.115606
Name: 24, dtype: float64

In [16]:
theme_list =  ['rien', 'rien', 'news/journal', 'bug','2024', 'site_down', 'femme_avortement_société', 'manga_japon',  'Bollywood', 'ethique', 'guerre_russie', 'soap_opera', 'petrole_climat_geothermie', 'justice', 'russie_anglais', 'série', 'rien', 'IA_voitures_autonomes', 'israel_gaza', 'films' , 'coree', 'music', 'energie', 'police_medicale', 'cdm_qatar', 'oppenheimer_manhattan', 'medical', 'euthanasie_souffrance', 'covid' , 'jeux_video_fantaisie' ]

In [17]:
features = nmf.transform(doc_term_matrix)

In [18]:
len(features)

200

In [19]:
len(features[0])

25

In [20]:
print(np.argmax(features[0]))

20

In [21]:
sorted_topics = [np.argsort(features[i]) for i in range(len(features))]
print(sorted_topics)

[array([10,  1,  2,  4, 17,  7, 15, 22, 11, 23,  3,  6,  8, 12,  5, 19, 21,
       18, 14,  9, 13, 16,  0, 24, 20], dtype=int64), array([12, 15, 14, 19, 10,  9, 16,  8,  6, 20, 21,  3,  1,  7, 18,  2, 11,
       13,  0, 24,  5, 23, 22, 17,  4], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 23, 12, 10,  9,  8,  6,
        5,  4,  3,  2,  1, 11, 24,  7], dtype=int64), array([24, 16, 21, 14, 13, 11, 10, 18,  9,  7, 22,  5,  2,  1,  8, 19,  3,
       20, 23,  4, 12,  6, 17, 15,  0], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 23, 12, 10,  9,  8,  6,
        5,  4,  3,  2,  1, 11, 24,  7], dtype=int64), array([ 0, 22, 20, 18, 17, 13, 23, 24,  1,  5,  3,  4, 10,  8, 11,  6,  2,
       12, 19, 15, 14, 16, 21,  9,  7], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 23, 24, 10,  9,  8,  7,
        6,  5,  4,  3,  2,  1, 11, 12], dtype=int64), array([12, 22, 21, 20, 19, 18, 17, 15, 14, 13, 23, 24, 10,  9,  8,  7,  6,
        4,  3,  2,  1, 11,  5, 16,  0], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 23, 24, 10,  9,  8,  7,
        6,  5,  4,  3,  2,  1, 11, 12], dtype=int64), array([24, 16, 19, 14, 13, 22, 17,  8,  9,  6,  5,  4,  3,  1,  7, 18, 21,
       23,  2, 12, 11, 10, 20,  0, 15], dtype=int64), array([ 0, 22, 20, 19, 17, 16, 15, 14, 23, 10, 12,  7,  6,  4,  3,  1,  9,
       24,  2, 18,  5,  8, 11, 21, 13], dtype=int64), array([ 0, 22, 20, 19, 18, 17, 14, 13, 23, 12,  8,  4,  3,  1, 24,  5, 11,
        2,  6, 10, 15,  9, 21,  7, 16], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 15, 14, 13, 23, 12, 10,  9,  8,  6,  5,
        4,  3,  2,  1, 11, 24,  7, 16], dtype=int64), array([12, 22, 21, 19, 17, 15, 14, 13, 23, 24,  8,  7,  5,  4,  3,  1,  9,
        0, 18, 10, 11,  6,  2, 16, 20], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 16, 14, 23, 11, 12,  8,  7,  6,  5,  4,
        3,  2,  1, 10, 24, 15, 13,  9], dtype=int64), array([12, 22, 21, 20, 19, 17, 16, 15, 14, 13, 23, 24, 10,  9,  8,  7,  6,
        5,  4,  3,  2,  1, 11, 18,  0], dtype=int64), array([24, 15, 14, 13, 23, 11, 10, 20,  8,  7, 22,  5,  4,  3,  2,  1, 16,
       21,  9, 19, 12,  6, 18, 17,  0], dtype=int64), array([ 0, 20, 18, 17, 15, 14, 13, 23, 11, 10, 12,  8,  7,  6,  5,  3,  2,
        1, 24,  4, 21, 22, 19,  9, 16], dtype=int64), array([24, 15, 14, 13, 23, 18, 10, 19,  8,  7, 20,  5, 21,  3,  2,  1, 16,
       17, 12, 11,  9, 22,  6,  0,  4], dtype=int64), array([24, 16, 21, 14, 13, 23, 20,  8,  9,  6,  5,  4,  3,  2,  1,  7, 19,
       22, 10,  0, 17, 12, 15, 11, 18], dtype=int64), array([ 0, 22, 20, 19, 18, 17, 16, 11, 10, 24,  8,  6,  2,  1,  9, 23, 21,
       14, 15, 13,  5,  7, 12,  3,  4], dtype=int64), array([ 0, 22, 21, 20, 19, 17, 16, 15, 14, 13, 23, 12, 10,  9,  8,  7,  6,
        5,  3,  2,  1, 11, 24,  4, 18], dtype=int64), array([24, 18, 19,  9, 15,  7,  8, 20, 22,  3,  1,  6, 17, 11, 13,  2, 10,
       12, 16, 23,  5, 14,  0, 21,  4], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 23, 12, 10,  9,  8,  7,
        6,  5,  4,  3,  2, 11, 24,  1], dtype=int64), array([ 0, 21, 20, 19, 14, 10,  7, 24,  1,  2,  3, 13, 11, 15,  6,  4,  5,
       22,  8, 17, 12,  9, 18, 16, 23], dtype=int64), array([24,  1,  2, 19, 18, 16, 14, 13,  8,  9, 10, 11, 12, 23, 15, 22,  5,
        6, 21,  7,  3,  4, 20,  0, 17], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 23, 12, 10,  9,  8,  7,
        6,  5,  4,  3,  2, 11, 24,  1], dtype=int64), array([12, 18, 17, 16, 15, 11, 10,  8, 24,  5,  3,  1, 22,  4, 21,  7, 20,
       23,  6,  2, 19, 13,  9, 14,  0], dtype=int64), array([ 9,  1,  2, 21,  5,  7,  8, 11, 23, 22, 10, 15, 16, 19,  6, 18, 14,
       24, 13, 20, 12,  4, 17,  3,  0], dtype=int64), array([24,  1,  3, 21, 18,  7,  8, 10, 11, 23, 16,  9,  2,  6, 14, 15, 12,
        5, 13, 22,  4, 19, 20,  0, 17], dtype=int64), array([ 0, 20, 19, 18, 15, 14, 23, 10, 12,  7,  6,  4,  3,  1,  8, 16, 11,
        5,  9, 21,  2, 22, 24, 13, 17], dtype=int64), array([12, 19, 18, 22, 16, 15, 14, 13, 23, 11, 21,  9,  8,  7,  6,  4,  3,
        2,  1, 20, 10,  5,  0, 17, 24], dtype=int64), array([12,  1,  2,  3,  4,  5,  6,  7,  8, 18, 10, 21, 23, 20, 17, 15,  9,
       16, 19, 14,  0, 22, 24, 13, 11], dtype=int64), array([ 0, 22, 21, 20, 18, 17, 16, 15, 14, 13, 12,  8,  7,  6,  5,  4,  3,
        2,  1, 10, 24, 11, 19, 23,  9], dtype=int64), array([12, 14, 21, 16,  7,  8,  1, 17,  4,  2, 22, 10, 11, 15, 18,  6,  5,
       23,  0,  9, 19, 13, 20,  3, 24], dtype=int64), array([24, 14, 13, 23, 11, 19,  9, 15, 16,  6,  5, 20, 22,  2,  7,  1,  8,
        0, 10,  3, 21, 18, 12,  4, 17], dtype=int64), array([12, 22, 20, 19, 18, 17, 15, 14, 13, 23, 11, 24,  9,  8,  7,  6,  5,
        4,  3,  2,  1, 10, 21, 16,  0], dtype=int64), array([ 0, 22, 21, 19, 18, 17, 15, 14, 13, 23, 11, 12,  9,  8,  7,  6,  5,
        4,  3,  1, 10, 24, 16,  2, 20], dtype=int64), array([ 0, 19, 13, 11, 10, 22, 15,  8,  5,  2,  1,  3,  4,  6, 23,  7, 17,
       24, 16, 18, 14, 21, 12,  9, 20], dtype=int64), array([12, 18, 19, 23, 11, 10,  9, 15, 22,  6,  5,  4,  3,  2,  1, 17,  7,
       24, 16, 21, 14,  8,  0, 13, 20], dtype=int64), array([12, 22, 21, 18, 15, 14, 23,  8, 24,  6,  5,  4,  3,  2,  1,  7, 10,
       11, 17, 19,  9, 20,  0, 16, 13], dtype=int64), array([ 0, 22, 21, 19, 18, 10,  9,  8, 12,  6,  5,  4,  3,  2,  1,  7, 20,
       15, 13, 16, 14, 11, 24, 23, 17], dtype=int64), array([12, 18, 16, 15, 22, 23, 11, 19,  9, 20,  7,  6,  5,  3,  1,  8, 14,
       21,  2, 10,  4, 24, 17,  0, 13], dtype=int64), array([ 0, 21, 16, 15, 14, 23, 11, 24,  2,  1,  3, 18,  7, 12, 10,  8,  6,
        5, 20, 13, 17, 22, 19,  4,  9], dtype=int64), array([10, 18, 17, 13, 23, 19,  9, 20,  6,  5,  4,  3,  2,  1,  7,  8, 22,
       11, 14, 24, 21, 12, 15,  0, 16], dtype=int64), array([24, 16, 15, 14, 23, 11, 10, 18,  9,  7,  6,  5,  4,  3,  2,  1,  8,
       19, 13, 22, 12,  0, 20, 17, 21], dtype=int64), array([ 0, 21, 19, 18, 17, 15, 14, 23, 10, 24,  7,  6,  5,  4,  3,  1,  9,
       16, 20,  8, 12, 11,  2, 22, 13], dtype=int64), array([ 0, 22, 21, 20, 19, 16, 15, 13, 23, 11, 24,  9,  7,  5,  2, 10,  1,
       14,  6,  8,  3, 12,  4, 17, 18], dtype=int64), array([ 0, 22, 20, 17, 16, 14, 13, 23, 11, 10, 12,  8,  7,  6,  5,  4,  3,
        2,  1,  9, 24, 19, 15, 21, 18], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 16, 15, 14, 23, 12, 10,  9,  8,  7,  6,
        5,  4,  3,  1, 24,  2, 13, 11], dtype=int64), array([ 0, 22, 21, 20, 19, 17, 16, 15, 14, 23, 11, 12,  7,  6,  5,  4,  1,
       24, 10,  8,  3,  2, 13, 18,  9], dtype=int64), array([24, 19, 18, 17, 16, 15, 14, 13, 23, 22, 10,  9,  8,  7,  6,  5,  4,
        2, 20, 21,  3,  1, 12,  0, 11], dtype=int64), array([12, 21, 20, 19, 17, 15, 23, 10,  9, 24,  6,  5,  1, 22,  0,  8,  7,
       11,  3,  4, 13, 14, 16, 18,  2], dtype=int64), array([12, 18, 17, 16, 15, 13, 23, 11, 10,  5,  2,  1,  8, 20, 21,  3,  4,
       22,  7,  6, 19, 24, 14,  0,  9], dtype=int64), array([ 0, 22, 21, 19, 18, 16, 14, 13, 23, 12,  8,  7,  6,  5,  4,  3,  1,
       24, 11, 10, 15,  2, 20, 17,  9], dtype=int64), array([ 0, 22, 21, 19, 18, 17, 16, 14, 13, 23, 11, 24,  8,  7,  6,  5,  4,
        3,  1, 10, 12, 15,  2, 20,  9], dtype=int64), array([ 0, 22, 20, 19, 18, 17, 16, 15, 14, 13, 23, 12, 10,  7,  4,  1, 11,
       24,  8,  3,  2,  6, 21,  9,  5], dtype=int64), array([12, 22, 21, 20, 18, 17, 16, 14, 13, 23, 11, 24,  9,  8,  7,  6,  5,
        4,  3,  2,  1, 10,  0, 15, 19], dtype=int64), array([24,  1,  2,  3,  4,  5, 22,  7,  8,  9, 21, 19, 18, 14, 12, 15, 16,
        6, 13,  0, 20, 23, 11, 10, 17], dtype=int64), array([24, 21, 16, 15, 14, 13, 22, 11, 10,  9,  7,  5,  4,  3,  2,  1, 20,
        6, 18,  8, 12,  0, 19, 17, 23], dtype=int64), array([ 0, 22, 21, 20, 17, 16, 15, 13, 23, 11, 12,  9,  8,  7,  6,  5,  4,
        3,  1, 24, 10, 19, 14,  2, 18], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 15, 14, 13, 11, 12,  8,  7,  6,  5,  4,
        3,  2,  1, 10, 24, 16,  9, 23], dtype=int64), array([24,  1,  3, 20, 19, 13, 23,  8, 11,  2, 12,  7, 15, 10,  4,  5, 17,
       22,  6,  0, 16,  9, 18, 14, 21], dtype=int64), array([24,  1,  3,  4, 21, 19,  7, 18, 10, 16, 15, 23, 22,  8, 17,  0, 11,
        6, 13,  5,  2, 12, 20,  9, 14], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 16, 15, 13, 23, 12, 10,  9,  8,  7,  6,
        5,  4,  3,  2,  1, 11, 24, 14], dtype=int64), array([ 0, 22, 21, 20, 19, 17, 16, 15, 14, 13, 23, 12, 10,  9,  8,  7,  6,
        5,  4,  3,  2,  1, 11, 24, 18], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 16, 15, 14, 13, 23, 12, 10,  9,  8,  6,  5,
        4,  3,  1, 11, 24,  2,  7, 17], dtype=int64), array([22,  1, 19,  3, 17,  5, 15,  7,  9, 10, 21, 23, 13, 11, 20,  2,  8,
        4,  6, 12, 14, 18, 16,  0, 24], dtype=int64), array([ 0, 22, 21, 20, 18, 17, 16, 14, 11, 12,  8,  7,  4,  3,  1,  9, 24,
       10,  5,  6, 13, 15, 23, 19,  2], dtype=int64), array([24, 16, 14, 21, 23, 22, 10, 19,  9,  5,  1,  8, 18,  4,  3,  6,  7,
       15,  2, 12, 17, 20, 13,  0, 11], dtype=int64), array([12,  1, 22,  3,  4, 21,  6,  7,  8,  9, 19, 17, 16, 13, 14, 15, 24,
       10,  2,  0,  5, 23, 11, 20, 18], dtype=int64), array([ 1,  3,  4,  5, 22,  7,  8, 11, 17, 16, 15, 21, 10, 24,  2, 12,  0,
        6, 13, 14, 20, 18, 23, 19,  9], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 15, 14, 11, 24,  9,  8,  7,  6,  5,  4,
        3,  1, 10, 12, 16, 23, 13,  2], dtype=int64), array([ 0, 22, 20, 19, 18, 17, 15, 14, 13, 23, 11, 12,  8,  7,  5,  4,  3,
        2,  1, 10, 24,  6, 16,  9, 21], dtype=int64), array([ 1,  2, 22,  4, 21,  8, 11, 17, 16,  6,  5, 10,  9,  0, 12,  7, 20,
        3, 13, 24, 15, 19, 18, 23, 14], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 23, 12, 10,  9,  8,  7,
        6,  5,  4,  3,  1, 11, 24,  2], dtype=int64), array([ 0, 22, 20, 19, 18, 17, 16, 15, 14, 13, 23, 12, 10,  9,  8,  7,  6,
        5,  4,  3,  2,  1, 11, 24, 21], dtype=int64), array([19,  1,  2, 13, 11, 10,  6,  8, 12, 16,  9,  7,  5, 20,  4, 14, 15,
       23,  3, 17,  0, 22, 21, 24, 18], dtype=int64), array([12, 22, 20, 19, 16, 15, 14, 13,  9, 24,  7,  6,  5,  4,  3,  2,  1,
       17, 10, 11, 21, 18,  8,  0, 23], dtype=int64), array([ 0, 22, 21, 20, 19, 17, 16, 15, 14, 13, 23, 12,  9,  8,  7,  6,  5,
        4,  3,  2,  1, 11, 10, 18, 24], dtype=int64), array([ 0, 22, 19, 18, 17, 16, 15, 13, 23, 10, 12,  8,  6,  5,  4,  3,  2,
        1,  9, 24,  7, 14, 21, 20, 11], dtype=int64), array([12,  1, 21,  3,  4, 20, 18,  8, 17, 11, 23, 14, 10,  5,  0,  6,  7,
       24, 22, 15,  2,  9, 19, 16, 13], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 16, 15, 14, 23, 24, 10,  9,  8,  7,  6,
        5,  4,  3,  2, 11,  1, 12, 13], dtype=int64), array([17,  1,  2, 18,  4,  5, 22,  7, 15,  9, 10, 20, 23, 12,  8,  3, 19,
       24, 14, 16,  6, 11, 21,  0, 13], dtype=int64), array([24,  1,  3,  4,  5,  6, 19,  8,  9, 18, 13, 14, 16, 10,  2, 11, 12,
       21,  7, 23, 17, 22, 15, 20,  0], dtype=int64), array([ 0, 21, 20, 19, 16, 14, 11,  8, 12,  5,  4,  2,  7,  1,  3, 22, 15,
       10,  6, 17, 24, 18,  9, 23, 13], dtype=int64), array([12, 19, 20, 13, 11, 10,  8, 21,  5,  4,  3,  1, 18,  7, 23, 17, 15,
        2,  6,  0, 14, 24,  9, 22, 16], dtype=int64), array([ 8, 15, 14, 13, 23, 11,  9, 21,  6,  5, 22,  1,  7, 10,  2, 16, 12,
        3, 24, 18, 19, 17,  0, 20,  4], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 23, 12, 10,  9,  8,  7,
        6,  5,  4,  3,  2, 11, 24,  1], dtype=int64), array([12, 19, 18, 17, 16, 15, 13, 23, 11, 10, 24,  8,  4,  3,  1, 14,  5,
        7, 22,  0,  6, 21,  9, 20,  2], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 23, 12, 10,  8,  7,  6,
        5,  4,  3, 11,  1, 24,  9,  2], dtype=int64), array([21,  1,  2, 22,  5, 18,  7,  8,  9, 16, 11, 23, 13, 14, 15,  3, 10,
        6, 19, 17, 12,  0, 24, 20,  4], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 16, 14, 23, 11, 12,  8,  3,  2,  1, 10,
       24,  6,  7,  5,  9,  4, 15, 13], dtype=int64), array([ 0, 21, 18, 17, 15, 23, 11,  9, 24,  6,  5,  4,  3,  2,  8,  1, 14,
       10, 12, 20, 22,  7, 19, 16, 13], dtype=int64), array([ 0, 22, 20, 18, 17, 16, 15, 14, 13, 23, 11, 12,  8,  7,  5,  4,  3,
        1, 24, 10, 19, 21,  6,  9,  2], dtype=int64), array([12, 20, 17, 15, 11, 10, 24,  3,  5,  4,  1,  2, 19,  8, 21, 22,  6,
        7, 14, 13, 18, 16, 23,  0,  9], dtype=int64), array([ 0, 19, 18, 16, 13, 23, 11, 10, 12,  5,  4,  3,  2,  1,  8, 24, 14,
       21,  7, 22,  6, 17, 15, 20,  9], dtype=int64), array([24,  1,  2,  3, 22,  5, 15, 13, 23, 10, 11, 16, 12,  6, 18,  4,  7,
        8, 21, 19,  0, 17, 14, 20,  9], dtype=int64), array([12, 14, 11, 10, 21,  7,  8,  5,  4,  3,  2,  1, 17, 20, 23, 16,  6,
       18, 24, 19, 15, 22,  9, 13,  0], dtype=int64), array([ 0, 22, 21, 20, 18, 15, 14, 13, 11, 10, 12,  7,  6,  3,  2,  9, 24,
        1,  8, 19,  4, 16, 23, 17,  5], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 23, 12, 10,  9,  8,  7,
        6,  4,  3,  2,  1, 11, 24,  5], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 23, 12, 10,  9,  8,  7,
        5,  4,  3,  2,  1, 11, 24,  6], dtype=int64), array([ 0, 20, 19, 18, 17, 16, 14, 13, 23, 11, 12,  9,  6,  4,  3,  2,  1,
       24, 10,  8,  7, 22, 21, 15,  5], dtype=int64), array([12,  1, 16, 20,  6,  7,  8, 11, 23, 13, 14, 15,  4, 10, 22, 17, 19,
       18,  2, 24,  3,  0, 21,  9,  5], dtype=int64), array([ 0, 21, 20, 19, 18, 17, 14, 11,  9, 12,  7,  6,  5,  4,  3,  2,  1,
        8, 24, 22, 13, 23, 16, 15, 10], dtype=int64), array([ 0, 16, 13, 23, 11, 10, 19,  9,  6,  5, 20, 21,  2,  1,  7, 18,  8,
       14, 15, 12,  3, 17, 22, 24,  4], dtype=int64), array([ 0, 22, 21, 20, 19, 17, 14, 24,  1,  3,  5,  2, 12,  6, 23,  9,  7,
        4, 13,  8, 16, 18, 11, 15, 10], dtype=int64), array([12, 19, 17, 16, 15, 14, 23, 11, 10, 24,  5,  3,  1, 21,  8,  2, 18,
        4,  7, 13, 20, 22,  9,  0,  6], dtype=int64), array([12, 21, 18, 17, 15, 23, 10, 24,  5,  4,  7,  3,  2,  1,  6, 22,  8,
       19, 11,  9, 14, 16, 20, 13,  0], dtype=int64), array([ 0, 18, 17, 14, 23, 10,  9, 12, 24,  6,  5,  4,  7,  2,  1, 11, 15,
       20,  8, 22, 13, 21, 19, 16,  3], dtype=int64), array([12, 19, 15, 13, 23, 11, 10, 17,  9, 21,  4,  3,  1,  8, 18,  7,  6,
        2, 14,  0, 24, 16, 22, 20,  5], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 23, 12, 10,  9,  8,  7,
        6,  5,  4,  3,  2, 11, 24,  1], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 23, 12, 10,  9,  8,  7,
        6,  5,  3,  2,  1, 11, 24,  4], dtype=int64), array([ 0, 22, 17, 14, 13, 23,  9,  8, 12,  6,  2,  1,  7,  5,  3, 20, 21,
       10, 11, 19, 15, 16, 24, 18,  4], dtype=int64), array([ 0, 16, 21, 13, 23,  6,  9,  3,  1,  5, 19,  2, 14,  7, 10, 11,  8,
       22, 17, 12, 15, 18, 24, 20,  4], dtype=int64), array([12, 17, 16, 15, 14, 13, 23, 10, 18,  9,  7,  6,  5,  4,  3,  2,  1,
        8, 21, 11, 24, 22, 19,  0, 20], dtype=int64), array([ 0, 21, 19, 18, 17, 13, 23, 10, 12,  7,  4,  3,  1, 24, 11, 22, 14,
        8,  5,  6, 15,  2, 20,  9, 16], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 16, 15, 14, 11, 12,  8,  7,  6,  3,  1,
       10, 24, 13,  4,  2,  5,  9, 23], dtype=int64), array([24, 14, 13, 23, 18, 19, 15,  8, 22,  5,  4,  3,  1,  7, 16,  2, 21,
       12,  6, 11, 17, 10,  0,  9, 20], dtype=int64), array([ 0, 22, 21, 18, 15, 23, 10,  9, 12,  7,  5,  4,  2,  1, 24, 13,  3,
        6, 19, 20,  8, 14, 11, 17, 16], dtype=int64), array([12, 18, 17, 16, 15, 14, 13, 21, 11, 19, 10,  8,  7,  6,  5,  4,  3,
        2,  1, 22, 20, 24,  0, 23,  9], dtype=int64), array([ 0, 22, 21, 20, 19, 17, 16, 13, 11, 10, 12,  6,  2,  1,  9, 24,  5,
        7,  4, 14, 18, 23, 15,  3,  8], dtype=int64), array([24,  1,  2,  3, 21, 18,  6,  7,  8, 15, 10, 11, 23, 13, 12, 16, 19,
       14, 22,  9, 20,  5,  4, 17,  0], dtype=int64), array([ 0, 19, 18, 17, 16, 14, 13, 11, 10, 24,  8,  7,  5,  4,  3,  1, 21,
       22,  2, 15, 12, 23, 20,  9,  6], dtype=int64), array([11,  2, 20, 19,  6,  7, 10, 21, 23, 13, 14, 15,  5, 16,  1,  8, 22,
        3,  9, 12,  4, 17, 18, 24,  0], dtype=int64), array([12, 21, 18, 17, 15, 14, 13, 23, 11, 10, 24,  8,  7,  5,  4,  3,  1,
       16,  2,  6, 22, 19, 20,  9,  0], dtype=int64), array([12, 22, 21, 20, 18, 17, 16, 14, 13, 10, 24,  8,  7,  6,  5,  4,  3,
        2,  1,  9, 23, 19, 15, 11,  0], dtype=int64), array([12,  2, 21,  4,  5,  6,  8, 19, 11, 23,  1, 10,  7, 14, 15,  0,  9,
        3, 18, 16, 22, 24, 17, 13, 20], dtype=int64), array([ 0, 21, 20, 18, 16, 15, 14, 13, 23, 11, 12,  8,  7,  4,  2,  1, 10,
        3,  5, 19, 17, 22,  9, 24,  6], dtype=int64), array([24, 15, 13, 11, 10,  8,  7,  9, 19, 21,  1,  6, 23,  2, 16, 14, 18,
       17,  3, 12,  0,  4, 20, 22,  5], dtype=int64), array([24,  1,  2,  3, 21,  5, 22, 16, 15,  9, 19, 14, 23, 13, 10,  6, 11,
        8, 20,  4,  7,  0, 18, 17, 12], dtype=int64), array([22, 19, 18, 17, 16, 15, 14, 13, 23, 11, 21,  9,  7,  6,  5,  4,  3,
        2,  1, 20,  8, 24, 12,  0, 10], dtype=int64), array([12, 22, 21, 20, 19, 18, 17, 16, 15, 14, 23, 24,  9,  8,  7,  6,  5,
        4,  3,  2,  1, 11, 10,  0, 13], dtype=int64), array([24, 14, 13, 11, 10, 17,  7, 19,  5,  3,  2,  1,  6, 21,  4, 22, 23,
       20,  9, 12, 15, 18,  0, 16,  8], dtype=int64), array([ 0, 20, 18, 17, 16, 13, 23, 11, 10, 12,  6,  5,  4,  2,  1, 24,  8,
       19, 14, 15,  7, 22,  3, 21,  9], dtype=int64), array([ 0, 22, 21, 17, 16, 13, 23, 11, 10, 12,  5,  4,  3,  2,  1, 24, 15,
        7,  8,  6, 18, 14, 19,  9, 20], dtype=int64), array([ 0, 22, 21, 20, 19, 17, 16, 15, 14, 13, 23, 12,  9,  8,  7,  6,  4,
        3,  2,  1, 11,  5, 18, 24, 10], dtype=int64), array([ 0, 22, 21, 20, 18, 17, 16, 15, 14, 13, 23, 12,  9,  8,  7,  6,  5,
        4,  3, 11, 24,  1,  2, 19, 10], dtype=int64), array([ 0, 22, 21, 19, 18, 17, 11, 10, 12,  7,  6,  5,  4,  3,  2,  1,  8,
       16, 23,  9, 15, 24, 14, 13, 20], dtype=int64), array([ 0, 22, 21, 19, 18, 17, 16, 15, 14, 13, 23, 12, 10,  9,  8,  7,  2,
       11, 24,  1,  5,  6,  3,  4, 20], dtype=int64), array([ 0, 22, 19, 18, 17, 16, 15, 14, 13, 23, 11, 24,  9,  8,  7,  6,  5,
        3,  2, 10,  1, 12,  4, 21, 20], dtype=int64), array([ 0, 20, 15, 14, 13, 23, 11, 10, 19, 18,  7,  5, 21,  3,  2,  8,  1,
        9,  6, 24, 12, 16, 22,  4, 17], dtype=int64), array([ 9, 22, 16, 15, 13, 23, 11,  8, 19,  5,  1,  7,  6,  3, 10, 21,  2,
        4, 14, 24, 12, 20, 18,  0, 17], dtype=int64), array([ 0, 21, 20, 18, 17, 16, 15, 13, 23, 11, 12,  9,  8,  7,  5,  4,  3,
        1, 24, 14, 19,  6,  2, 10, 22], dtype=int64), array([ 0, 20, 19, 17, 16, 15, 13, 23, 11, 10, 24,  8,  6,  3,  9,  1,  7,
        2,  4,  5, 14, 12, 21, 18, 22], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 23, 12,  9,  8,  7,  6,
        5,  4,  3,  2,  1, 11, 24, 10], dtype=int64), array([12, 22, 21, 20, 19, 18, 17, 15, 14, 13, 23, 24,  9,  8,  7,  6,  5,
        4,  2,  1, 11, 10,  3,  0, 16], dtype=int64), array([12, 22, 21, 19, 18, 16, 15, 14,  9, 24,  7,  6,  4,  3,  2,  1,  8,
       10, 23,  0, 11, 20, 17, 13,  5], dtype=int64), array([ 1,  5, 18, 10, 11, 23,  3, 22, 24,  2, 16,  9,  8, 14, 15,  4, 12,
       21, 13,  6,  7, 17,  0, 20, 19], dtype=int64), array([ 9, 16, 13, 11, 20, 19,  3,  2,  1,  5, 14, 21,  6,  7,  8, 10, 15,
       22,  4,  0, 24, 12, 23, 17, 18], dtype=int64), array([24, 21, 16, 15, 13, 23, 11, 18, 22,  7,  6,  5,  4,  3,  2,  1,  8,
       19, 10, 14, 12, 20,  0, 17,  9], dtype=int64), array([12, 16, 19, 14, 23, 22, 17,  8,  9,  6,  5,  4,  3,  2,  1,  7, 18,
       13, 10, 24, 15, 11, 20,  0, 21], dtype=int64), array([ 0, 22, 19, 11,  9,  6, 12, 24,  1,  2,  5, 16,  7,  8, 10, 13, 14,
       15,  4,  3, 17, 23, 18, 21, 20], dtype=int64), array([ 0, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 23, 12, 10,  9,  8,  7,
        6,  5,  4,  3,  2, 11, 24,  1], dtype=int64), array([ 0, 22, 21, 19, 16, 14, 11,  8, 12,  6,  5,  3,  2,  1,  7, 24, 23,

In [122]:
first_topic = []
second_topic = []
third_topic = []
for tops in sorted_topics:
    first_topic.append(theme_list[tops[-1]])
    second_topic.append(theme_list[tops[-2]])
    third_topic.append(theme_list[tops[-3]])

df['First_topic'] = first_topic
df['Second_topic'] = second_topic
df['Third_topic'] = third_topic

In [123]:
df

,Links,Reachable,Code,Text,First_topic,Second_topic,Third_topic
0,https://www.programme-television.org/news-tv/I...,True,200,Télé\nIci tout commence : Mehdi sous le choc f...,rien,série,films
1,https://www.philomag.com/articles/leurope-et-l...,True,200,L’Europe et la guerre en Ukraine vues par un p...,guerre_russie,rien,oppenheimer_manhattan
2,https://nouvelles-dujour.com/jerrod-carmichael...,True,200,Account Suspended\nThis Account has been suspe...,site_down,jeux_video_fantaisie,covid
3,https://lbe.news/les-gagnants-des-80e-golden-g...,True,200,Unknown HostThis server does not serve the hos...,bug,vie_famille,femme_avortement_société
4,https://www.latribune.ca/2023/01/13/captivant-...,True,200,Deux couples aux antipodes des privilèges fina...,films,rien,news/journal
...,...,...,...,...,...,...,...
679,http://www.critictoo.com/bilans-de-saisons/per...,True,200,Tout commençait par un crash. La famille Robin...,série,rien,IA_voitures_autonomes
680,https://asialyst.com/fr/2020/01/17/inde-bangla...,True,200,Films d'Asie du Sud\nUne semaine de cinéma ind...,films,covid,guerre_russie
681,https://www.lexpress.fr/actualite/societe/reto...,True,200,"Ce retour aux 90 kilomètres-heure, ils l'ont p...",rien,horloge_enigme,covid
682,https://www.lemonde.fr/culture/article/2020/01...,True,200,ARTE - MARDI 21 JANVIER À 20 H 50 - DOCUMENTAI...,israel_gaza,covid,rien
683,https://business-cool.com/actualites/business-...,True,200,Grenoble École de Management ouvre son laborat...,rien,covid,jeux_video_fantaisie

In [126]:
df = df[df['First_topic'] != 'bug'][df['First_topic'] != 'site_down']

C:\Users\Emile\AppData\Local\Temp\ipykernel_37708\549096651.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[df['First_topic'] != 'bug'][df['First_topic'] != 'site_down']

In [127]:
df.to_excel("results/Topics.xlsx", index=False)

In [128]:
len(df)

660